# Generated by Django 2.2.26 on 2022-08-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_downvotepost_likecomment_post_postcomment_postmedia_reportpost_upvotepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='title',
        ),
        migrations.AddField(
            model_name='customtext',
            name='sdfadgag',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
